{
    'name': "SMS Framework",
    'version': "1.0",
    'author': "Sythil",
    'category': "Tools",
    'summary':'Allows you to send and receive smses from multiple gateways',
    'description':'Allows you to send and receive smses from multiple gateways',    
    'license':'LGPL-3',
    'data': [
        'views/sms.xml',
        'views/res_partner.xml',
        'views/sms_message.xml',
        'views/sms_template.xml',
        'views/sms_account.xml',
        'views/sms_number.xml',
        'views/sms_compose.xml',
        'data/ir.cron.csv',
        'data/res.country.csv',
    ],
    'demo': [],
    'depends': [],
    'images':[
        'static/description/1.jpg',
    ],
    'installable': True,
}