{
    'name': "Search Engine Marketing Toolkit",
    'version': "1.0.0",
    'author': "Sythil Tech",
    'category': "Tools",
    'summary': "Set of tools to help with Search Engine Marketing / Optimisation",
    'description': "Set of tools to help with Search Engine Marketing / Optimisation",
    'license':'LGPL-3',
    'data': [
        'data/sem.check.category.xml',
        'data/sem.check.xml',
        'data/sem.search_engine.xml',
        'data/res.groups.xml',
        'views/sem_client_views.xml',
        'views/sem_client_website_views.xml',
        'views/sem_client_website_keyword_views.xml',
        'views/sem_check_views.xml',
        'views/sem_check_category_views.xml',
        'views/sem_report_seo_views.xml',
        'views/sem_report_competition_views.xml',
        'views/sem_report_search_views.xml',
        'views/sem_geo_target_views.xml',
        'views/sem_settings_views.xml',
        'views/menus.xml',
        'views/sem_seo_toolkit_templates.xml',
        'security/ir.model.access.csv',
    ],
    'depends': ['google_account'],
    'installable': True,
}