{
    'name': "Search Engine Marketing Toolkit",
    'version': "1.1.3",
    'author': "Sythil Tech",
    'category': "Tools",
    'summary': "Set of tools to help with Search Engine Marketing / Optimisation",
    'description': "Set of tools to help with Search Engine Marketing / Optimisation",
    'license':'LGPL-3',
    'data': [
        'data/sem.depend.xml',
        'data/sem.check.category.xml',
        'data/sem.metric.xml',
        'data/sem.check.xml',
        'data/sem.search.engine.xml',
        'data/res.groups.xml',
        'data/sem.search.device.xml',
        'views/sem_client_website_page_views.xml',
        'views/sem_client_website_views.xml',
        'views/sem_client_listing_views.xml',
        'views/sem_client_views.xml',
        'views/sem_metric_views.xml',
        'views/sem_check_views.xml',
        'views/sem_check_category_views.xml',
        'views/sem_report_website_page_views.xml',
        'views/sem_report_website_views.xml',
        'views/sem_report_competition_views.xml',
        'views/sem_report_search_views.xml',
        'views/sem_report_ranking_views.xml',
        'views/sem_report_google_business_views.xml',
        'views/sem_search_context_views.xml',
        'views/sem_search_context_wizard_views.xml',
        'views/sem_search_device_views.xml',
        'views/sem_search_results_views.xml',
        'views/sem_track_views.xml',
        'views/sem_settings_views.xml',
        'views/menus.xml',
        'views/sem_seo_toolkit_templates.xml',
        'security/ir.model.access.csv',
    ],
    'depends': ['google_account'],
    'installable': True,
}