{
    'name': "Website Color Palettes",
    'version': "1.1",
    'author': "Sythil Tech",
    'category': "Website",
    'support': "steven@sythiltech.com.au",
    'summary': "Define custom css color codes to style your website",
    'description': "Define custom css color codes to style your website",
    'license':'LGPL-3',
    'data': [
        'data/website.style.fontfamily.csv',
        'data/website.style.htmltag.csv',
        'data/website.style.profile.csv',
        'data/website.style.profile.less.csv',
        'views/website.xml',
        'views/website_templates.xml',
        'security/ir.model.access.csv',
    ],
    'demo': [],
    'images':[
        'static/description/1.jpg',
    ],
    'depends': ['website'],
    'installable': True,
}